volumes:
  pgdata:
    driver: local

services:
  app:
    command: ["sleep","infinity"]
    container_name: haskell-elm
    build:
      context: .
    volumes:
      - ~/.ssh:/home/ubuntu/.ssh
      - ~/.config/nvim:/home/ubuntu/.config/nvim
      - ./:/home/ubuntu/devcontainer
    ports:
      - "8080:8080"
      - "32873:32873"
  db:
    image: postgres
    container_name: haskell-elm-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

