volumes:
  sqldata:
    driver: local

services:
  app:
    container_name: dotnetcore-react
    command: ["sleep", "infinity"]
    build:
      context: .
    volumes:
      - ~/.ssh:/home/ubuntu/.ssh
      - ~/.config/nvim:/home/ubuntu/.config/nvim
      - ./:/home/ubuntu/devcontainer
    ports:
      - "5109:5109"
      - "5173:5173"
  db:
    container_name: dotnetcore-react-mssql
    build:
      context: ./mssql
    volumes:                    
      - sqldata:/var/opt/mssql
    ports:
      - "1433:1433"
